version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: routes.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/app
    restart: unless-stopped
